version: "3.8"

services:

  accounts:
    image: ratzcom/accounts-service:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - ratzcom-network

  loans:
    image: ratzcom/loans-service:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - ratzcom-network

  cards:
    image: ratzcom/cards-service:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - ratzcom-network

networks:
  ratzcom-network: